name: Build Project

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'
    tags:
      - '*'
  pull_request:
    branches:
      - 'release'
    tags:
      - '*'

jobs:
  buildWebPlatform:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # Make space
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          build-mount-path: '/var/lib/docker'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          
      # Checkout    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      #      # Test
      #      - name: Run tests
      #        uses: game-ci/unity-test-runner@v4
      #        env:
      #          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #        with:
      #          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: BuildWebPlatform
          path: build